### ISSUE TITLE
VMplayer 14

### ISSUE THREAD

**Issue by RobbiNespu** [hhemied/FixVMware#1]
Hi there, seem this script check VM Workstation Pro, not VM Player.

I tried to mod with checking VMplayer 
```
$ git diff fixvm.py
diff --git a/fixvm.py b/fixvm.py
old mode 100644
new mode 100755
index 74acd94..9fffb1d
--- a/fixvm.py
+++ b/fixvm.py
@@ -53,7 +53,7 @@ def vmISOK():
 
 # Checking whether Vmware installed or not [tested with VMWare Workstation]
 def vmwareInstalled():
-    if os.path.exists("/usr/bin/vmware"):
+    if os.path.exists("/usr/bin/vmplayer"):
         return True
     else:
         print("VMWare is not installed...")
```
But still failed to execute properly:
```
$ sudo ./fixvm.py
 
*************FIXVMware************************************
 - Run the script on clear and update system
 - Script is compatible with Fedora systems

 - Please let me know if you face any trouble
 *********************************************************
 This script is disigned and built by Hazem Hemied(hhemied)
 **********************************************************
 
 Installing Dependencies ...
 Manipulating your system files ...
vmmon-only/
vmmon-only/Makefile.normal
vmmon-only/.vmmon.ko.cmd
vmmon-only/modules.order
vmmon-only/README
vmmon-only/bootstrap/
vmmon-only/bootstrap/.monLoaderVmmon.o.cmd
vmmon-only/bootstrap/monLoader.c
vmmon-only/bootstrap/bootstrap.o
vmmon-only/bootstrap/.monLoader.o.cmd
vmmon-only/bootstrap/monLoaderVmmon.c
vmmon-only/bootstrap/bootstrap.c
vmmon-only/bootstrap/monLoaderVmmon.o
vmmon-only/bootstrap/.bootstrap.o.cmd
vmmon-only/bootstrap/monLoader.o
vmmon-only/.vmmon.mod.o.cmd
vmmon-only/common/
vmmon-only/common/phystrack.o
vmmon-only/common/comport.c
vmmon-only/common/cpuid.o
vmmon-only/common/hostKernel.h
vmmon-only/common/apic.c
vmmon-only/common/vmx86.h
vmmon-only/common/.cpuid.o.cmd
vmmon-only/common/hostifGlobalLock.h
vmmon-only/common/phystrack.c
vmmon-only/common/.phystrack.o.cmd
vmmon-only/common/.vmx86.o.cmd
vmmon-only/common/vmx86.o
vmmon-only/common/apic.o
vmmon-only/common/cpuid.h
vmmon-only/common/task.o
vmmon-only/common/hostif.h
vmmon-only/common/.hashFunc.o.cmd
vmmon-only/common/task.h
vmmon-only/common/vmx86.c
vmmon-only/common/memtrack.c
vmmon-only/common/.memtrack.o.cmd
vmmon-only/common/.apic.o.cmd
vmmon-only/common/cpuid.c
vmmon-only/common/apic.h
vmmon-only/common/hostifMem.h
vmmon-only/common/phystrack.h
vmmon-only/common/hashFunc.o
vmmon-only/common/.comport.o.cmd
vmmon-only/common/.task.o.cmd
vmmon-only/common/task.c
vmmon-only/common/comport.o
vmmon-only/common/comport.h
vmmon-only/common/memtrack.o
vmmon-only/common/memtrack.h
vmmon-only/common/hashFunc.c
vmmon-only/Makefile
vmmon-only/Module.symvers
vmmon-only/.tmp_versions/
vmmon-only/.tmp_versions/vmmon.mod
vmmon-only/driver-4.11.8-300.fc26.x86_64/
vmmon-only/driver-4.11.8-300.fc26.x86_64/driver.d
vmmon-only/driver-4.11.8-300.fc26.x86_64/hostif.d
vmmon-only/vmmon.mod.o
vmmon-only/vmmon.mod.c
vmmon-only/vmmon.ko
vmmon-only/vmmon.o
vmmon-only/.vmmon.o.cmd
vmmon-only/vmcore/
vmmon-only/vmcore/moduleloop.o
vmmon-only/vmcore/driver_vmcore.h
vmmon-only/vmcore/.moduleloop.o.cmd
vmmon-only/vmcore/moduleloop.c
vmmon-only/autoconf/
vmmon-only/autoconf/tsc_khz.c
vmmon-only/autoconf/smpcall.c
vmmon-only/autoconf/geninclude.c
vmmon-only/linux/
vmmon-only/linux/hostif.o
vmmon-only/linux/driver.c
vmmon-only/linux/driver.h
vmmon-only/linux/vmhost.h
vmmon-only/linux/driver.o
vmmon-only/linux/driverLog.c
vmmon-only/linux/driverLog.h
vmmon-only/linux/driverLog.o
vmmon-only/linux/vmmonInt.h
vmmon-only/linux/hostif_priv.h
vmmon-only/linux/hostif.c
vmmon-only/linux/.hostif.o.cmd
vmmon-only/linux/.driver.o.cmd
vmmon-only/linux/.driverLog.o.cmd
vmmon-only/COPYING
vmmon-only/Makefile.kernel
vmmon-only/include/
vmmon-only/include/x86paging_common.h
vmmon-only/include/vm_basic_math.h
vmmon-only/include/compat_version.h
vmmon-only/include/vm_basic_asm_x86_common.h
vmmon-only/include/vcpuset_types.h
vmmon-only/include/address_defs.h
vmmon-only/include/hashFunc.h
vmmon-only/include/x86svm.h
vmmon-only/include/vm_asm_x86_64.h
vmmon-only/include/x86types.h
vmmon-only/include/x86sel.h
vmmon-only/include/vmware.h
vmmon-only/include/vm_assert.h
vmmon-only/include/x86vtinstr.h
vmmon-only/include/cpu_defs.h
vmmon-only/include/x86vt-exit-reasons.h
vmmon-only/include/vm_basic_defs.h
vmmon-only/include/x86apic.h
vmmon-only/include/compat_pci.h
vmmon-only/include/community_source.h
vmmon-only/include/x86segdescrs.h
vmmon-only/include/modulecallstructs.h
vmmon-only/include/vm_basic_types.h
vmmon-only/include/compat_sched.h
vmmon-only/include/compat_page.h
vmmon-only/include/uccostTable.h
vmmon-only/include/vmware_pack_end.h
vmmon-only/include/compat_pgtable.h
vmmon-only/include/pagelist.h
vmmon-only/include/compat_autoconf.h
vmmon-only/include/vm_basic_asm_x86_64.h
vmmon-only/include/vmware_pack_begin.h
vmmon-only/include/vm_basic_asm.h
vmmon-only/include/crossgdt.h
vmmon-only/include/perfctr_generic.h
vmmon-only/include/vm_basic_asm_x86.h
vmmon-only/include/overheadmem_types.h
vmmon-only/include/compat_semaphore.h
vmmon-only/include/compat_kernel.h
vmmon-only/include/pageLock_defs.h
vmmon-only/include/rateconv.h
vmmon-only/include/x86_basic_defs.h
vmmon-only/include/ptsc.h
vmmon-only/include/x86perfctr.h
vmmon-only/include/basic_initblock.h
vmmon-only/include/x86desc.h
vmmon-only/include/versioned_atomic.h
vmmon-only/include/pcip_defs.h
vmmon-only/include/compat_ioport.h
vmmon-only/include/x86msr.h
vmmon-only/include/pshare_ext.h
vmmon-only/include/compat_spinlock.h
vmmon-only/include/monitorAction_exported.h
vmmon-only/include/usercalldefs.h
vmmon-only/include/vmmem_shared.h
vmmon-only/include/monLoader.h
vmmon-only/include/x86vendor.h
vmmon-only/include/iocontrols.h
vmmon-only/include/driver-config.h
vmmon-only/include/includeCheck.h
vmmon-only/include/circList.h
vmmon-only/include/compat_module.h
vmmon-only/include/contextinfo.h
vmmon-only/include/vmware_pack_init.h
vmmon-only/include/pgtbl.h
vmmon-only/include/vmm_constants.h
vmmon-only/include/x86paging_64.h
vmmon-only/include/monAddrLayout.h
vmmon-only/include/bootstrap_vmm.h
vmmon-only/include/vm_asm_x86.h
vmmon-only/include/vm_asm.h
vmmon-only/include/vm_time.h
vmmon-only/include/compat_highmem.h
vmmon-only/include/modulecall.h
vmmon-only/include/vcpuid.h
vmmon-only/include/vcpuset.h
vmmon-only/include/x86vt.h
vmmon-only/include/x86cpuid.h
vmmon-only/include/cpuid_info.h
vmmon-only/include/compat_cred.h
vmmon-only/include/compat_interrupt.h
vmmon-only/include/x86cpuid_asm.h
vmmon-only/include/vm_pagetable.h
vmmon-only/include/initblock.h
vmmon-only/include/monLoaderLog.h
vmmon-only/include/memDefaults.h
vmmon-only/include/numa_defs.h
vmmon-only/include/x86vt-vmcs-fields.h
vmmon-only/include/vm_atomic.h
vmmon-only/include/mon_assert.h
vmnet-only/
vmnet-only/compat_version.h
vmnet-only/vm_basic_asm_x86_common.h
vmnet-only/.procfs.o.cmd
vmnet-only/Makefile.normal
vmnet-only/userif.c
vmnet-only/bridge.c
vmnet-only/userif.o
vmnet-only/vnet.h
vmnet-only/modules.order
vmnet-only/vm_assert.h
vmnet-only/.bridge.o.cmd
vmnet-only/vm_basic_defs.h
vmnet-only/net.h
vmnet-only/community_source.h
vmnet-only/.hub.o.cmd
vmnet-only/vm_basic_types.h
vmnet-only/.vnetEvent.o.cmd
vmnet-only/bridge.o
vmnet-only/driver.c
vmnet-only/smac.h
vmnet-only/vmware_pack_end.h
vmnet-only/Makefile
vmnet-only/compat_autoconf.h
vmnet-only/vm_basic_asm_x86_64.h
vmnet-only/vmware_pack_begin.h
vmnet-only/Module.symvers
vmnet-only/vm_basic_asm.h
vmnet-only/procfs.c
vmnet-only/.netif.o.cmd
vmnet-only/smac.o
vmnet-only/vm_basic_asm_x86.h
vmnet-only/.vmnet.mod.o.cmd
vmnet-only/smac.c
vmnet-only/vm_oui.h
vmnet-only/.tmp_versions/
vmnet-only/.tmp_versions/vmnet.mod
vmnet-only/smac_compat.h
vmnet-only/.vnetUserListener.o.cmd
vmnet-only/vnetEvent.h
vmnet-only/vnetUserListener.c
vmnet-only/vnetFilter.h
vmnet-only/compat_sock.h
vmnet-only/vnetInt.h
vmnet-only/driver.o
vmnet-only/netif.c
vmnet-only/monitorAction_exported.h
vmnet-only/vnetFilterInt.h
vmnet-only/hub.c
vmnet-only/vm_device_version.h
vmnet-only/vmnet.o
vmnet-only/smac_compat.o
vmnet-only/nfhook_uses_skb.c
vmnet-only/vnetUserListener.o
vmnet-only/netdev_has_net.c
vmnet-only/driver-config.h
vmnet-only/includeCheck.h
vmnet-only/compat_module.h
vmnet-only/vmware_pack_init.h
vmnet-only/vmnet.ko
vmnet-only/compat_skbuff.h
vmnet-only/vnetEvent.c
vmnet-only/vmnetInt.h
vmnet-only/compat_netdevice.h
vmnet-only/.smac_compat.o.cmd
vmnet-only/vmnet.mod.o
vmnet-only/hub.o
vmnet-only/smac_compat.c
vmnet-only/.userif.o.cmd
vmnet-only/COPYING
vmnet-only/procfs.o
vmnet-only/.vmnet.o.cmd
vmnet-only/Makefile.kernel
vmnet-only/geninclude.c
vmnet-only/skblin.c
vmnet-only/netif.o
vmnet-only/vmnet.mod.c
vmnet-only/x86cpuid.h
vmnet-only/.vmnet.ko.cmd
vmnet-only/.smac.o.cmd
vmnet-only/netdev_has_dev_net.c
vmnet-only/vnetEvent.o
vmnet-only/.driver.o.cmd
vmnet-only/vnetKernel.h
vmnet-only/vm_atomic.h
Using kernel build system.
make -C /lib/modules/4.12.8-300.fc26.x86_64/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[1]: Entering directory '/usr/src/kernels/4.12.8-300.fc26.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/kernels/4.12.8-300.fc26.x86_64'
make -C $PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= postbuild
make[1]: Entering directory '/usr/lib/vmware/modules/source/vmmon-only'
make[1]: 'postbuild' is up to date.
make[1]: Leaving directory '/usr/lib/vmware/modules/source/vmmon-only'
cp -f vmmon.ko ./../vmmon.o
Using kernel build system.
make -C /lib/modules/4.12.8-300.fc26.x86_64/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[1]: Entering directory '/usr/src/kernels/4.12.8-300.fc26.x86_64'
Package kernel-devel-4.12.8-300.fc26.x86_64 is already installed, skipping.
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/kernels/4.12.8-300.fc26.x86_64'
make -C $PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= postbuild
make[1]: Entering directory '/usr/lib/vmware/modules/source/vmnet-only'
make[1]: 'postbuild' is up to date.
make[1]: Leaving directory '/usr/lib/vmware/modules/source/vmnet-only'
cp -f vmnet.ko ./../vmnet.o
vmnet-only/
vmnet-only/compat_version.h
vmnet-only/vm_basic_asm_x86_common.h
vmnet-only/.procfs.o.cmd
vmnet-only/Makefile.normal
vmnet-only/userif.c
vmnet-only/bridge.c
vmnet-only/userif.o
vmnet-only/vnet.h
vmnet-only/modules.order
vmnet-only/vm_assert.h
vmnet-only/.bridge.o.cmd
vmnet-only/vm_basic_defs.h
vmnet-only/net.h
vmnet-only/community_source.h
vmnet-only/.hub.o.cmd
vmnet-only/vm_basic_types.h
vmnet-only/.vnetEvent.o.cmd
vmnet-only/bridge.o
vmnet-only/driver.c
vmnet-only/smac.h
vmnet-only/vmware_pack_end.h
vmnet-only/Makefile
vmnet-only/compat_autoconf.h
vmnet-only/vm_basic_asm_x86_64.h
vmnet-only/vmware_pack_begin.h
vmnet-only/Module.symvers
vmnet-only/vm_basic_asm.h
vmnet-only/procfs.c
vmnet-only/.netif.o.cmd
vmnet-only/smac.o
vmnet-only/vm_basic_asm_x86.h
vmnet-only/.vmnet.mod.o.cmd
vmnet-only/smac.c
vmnet-only/vm_oui.h
vmnet-only/.tmp_versions/
vmnet-only/.tmp_versions/vmnet.mod
vmnet-only/smac_compat.h
vmnet-only/.vnetUserListener.o.cmd
vmnet-only/vnetEvent.h
vmnet-only/vnetUserListener.c
vmnet-only/vnetFilter.h
vmnet-only/compat_sock.h
vmnet-only/vnetInt.h
vmnet-only/driver.o
vmnet-only/netif.c
vmnet-only/monitorAction_exported.h
vmnet-only/vnetFilterInt.h
vmnet-only/hub.c
vmnet-only/vm_device_version.h
vmnet-only/vmnet.o
vmnet-only/smac_compat.o
vmnet-only/nfhook_uses_skb.c
vmnet-only/vnetUserListener.o
vmnet-only/netdev_has_net.c
vmnet-only/driver-config.h
vmnet-only/includeCheck.h
vmnet-only/compat_module.h
vmnet-only/vmware_pack_init.h
vmnet-only/vmnet.ko
vmnet-only/compat_skbuff.h
vmnet-only/vnetEvent.c
vmnet-only/vmnetInt.h
vmnet-only/compat_netdevice.h
vmnet-only/.smac_compat.o.cmd
vmnet-only/vmnet.mod.o
vmnet-only/hub.o
vmnet-only/smac_compat.c
vmnet-only/.userif.o.cmd
vmnet-only/COPYING
vmnet-only/procfs.o
vmnet-only/.vmnet.o.cmd
vmnet-only/Makefile.kernel
vmnet-only/geninclude.c
vmnet-only/skblin.c
vmnet-only/netif.o
vmnet-only/vmnet.mod.c
vmnet-only/x86cpuid.h
vmnet-only/.vmnet.ko.cmd
vmnet-only/.smac.o.cmd
vmnet-only/netdev_has_dev_net.c
vmnet-only/vnetEvent.o
vmnet-only/.driver.o.cmd
vmnet-only/vnetKernel.h
vmnet-only/vm_atomic.h
vmmon-only/
vmmon-only/Makefile.normal
vmmon-only/.vmmon.ko.cmd
vmmon-only/modules.order
vmmon-only/README
vmmon-only/bootstrap/
vmmon-only/bootstrap/.monLoaderVmmon.o.cmd
vmmon-only/bootstrap/monLoader.c
vmmon-only/bootstrap/bootstrap.o
vmmon-only/bootstrap/.monLoader.o.cmd
vmmon-only/bootstrap/monLoaderVmmon.c
vmmon-only/bootstrap/bootstrap.c
vmmon-only/bootstrap/monLoaderVmmon.o
vmmon-only/bootstrap/.bootstrap.o.cmd
vmmon-only/bootstrap/monLoader.o
vmmon-only/.vmmon.mod.o.cmd
vmmon-only/common/
vmmon-only/common/phystrack.o
vmmon-only/common/comport.c
vmmon-only/common/cpuid.o
vmmon-only/common/hostKernel.h
vmmon-only/common/apic.c
vmmon-only/common/vmx86.h
vmmon-only/common/.cpuid.o.cmd
vmmon-only/common/hostifGlobalLock.h
vmmon-only/common/phystrack.c
vmmon-only/common/.phystrack.o.cmd
vmmon-only/common/.vmx86.o.cmd
vmmon-only/common/vmx86.o
vmmon-only/common/apic.o
vmmon-only/common/cpuid.h
vmmon-only/common/task.o
vmmon-only/common/hostif.h
vmmon-only/common/.hashFunc.o.cmd
vmmon-only/common/task.h
vmmon-only/common/vmx86.c
vmmon-only/common/memtrack.c
vmmon-only/common/.memtrack.o.cmd
vmmon-only/common/.apic.o.cmd
vmmon-only/common/cpuid.c
vmmon-only/common/apic.h
vmmon-only/common/hostifMem.h
vmmon-only/common/phystrack.h
vmmon-only/common/hashFunc.o
vmmon-only/common/.comport.o.cmd
vmmon-only/common/.task.o.cmd
vmmon-only/common/task.c
vmmon-only/common/comport.o
vmmon-only/common/comport.h
vmmon-only/common/memtrack.o
vmmon-only/common/memtrack.h
vmmon-only/common/hashFunc.c
vmmon-only/Makefile
vmmon-only/Module.symvers
vmmon-only/.tmp_versions/
vmmon-only/.tmp_versions/vmmon.mod
vmmon-only/driver-4.11.8-300.fc26.x86_64/
vmmon-only/driver-4.11.8-300.fc26.x86_64/driver.d
vmmon-only/driver-4.11.8-300.fc26.x86_64/hostif.d
vmmon-only/vmmon.mod.o
vmmon-only/vmmon.mod.c
vmmon-only/vmmon.ko
vmmon-only/vmmon.o
vmmon-only/.vmmon.o.cmd
vmmon-only/vmcore/
vmmon-only/vmcore/moduleloop.o
vmmon-only/vmcore/driver_vmcore.h
vmmon-only/vmcore/.moduleloop.o.cmd
vmmon-only/vmcore/moduleloop.c
vmmon-only/autoconf/
vmmon-only/autoconf/tsc_khz.c
vmmon-only/autoconf/smpcall.c
vmmon-only/autoconf/geninclude.c
vmmon-only/linux/
vmmon-only/linux/hostif.o
vmmon-only/linux/driver.c
vmmon-only/linux/driver.h
vmmon-only/linux/vmhost.h
vmmon-only/linux/driver.o
vmmon-only/linux/driverLog.c
vmmon-only/linux/driverLog.h
vmmon-only/linux/driverLog.o
vmmon-only/linux/vmmonInt.h
vmmon-only/linux/hostif_priv.h
vmmon-only/linux/hostif.c
vmmon-only/linux/.hostif.o.cmd
vmmon-only/linux/.driver.o.cmd
vmmon-only/linux/.driverLog.o.cmd
vmmon-only/COPYING
vmmon-only/Makefile.kernel
vmmon-only/include/
vmmon-only/include/x86paging_common.h
vmmon-only/include/vm_basic_math.h
vmmon-only/include/compat_version.h
vmmon-only/include/vm_basic_asm_x86_common.h
vmmon-only/include/vcpuset_types.h
vmmon-only/include/address_defs.h
vmmon-only/include/hashFunc.h
vmmon-only/include/x86svm.h
vmmon-only/include/vm_asm_x86_64.h
vmmon-only/include/x86types.h
vmmon-only/include/x86sel.h
vmmon-only/include/vmware.h
vmmon-only/include/vm_assert.h
vmmon-only/include/x86vtinstr.h
vmmon-only/include/cpu_defs.h
vmmon-only/include/x86vt-exit-reasons.h
vmmon-only/include/vm_basic_defs.h
vmmon-only/include/x86apic.h
vmmon-only/include/compat_pci.h
vmmon-only/include/community_source.h
vmmon-only/include/x86segdescrs.h
vmmon-only/include/modulecallstructs.h
vmmon-only/include/vm_basic_types.h
vmmon-only/include/compat_sched.h
vmmon-only/include/compat_page.h
vmmon-only/include/uccostTable.h
vmmon-only/include/vmware_pack_end.h
vmmon-only/include/compat_pgtable.h
vmmon-only/include/pagelist.h
vmmon-only/include/compat_autoconf.h
vmmon-only/include/vm_basic_asm_x86_64.h
vmmon-only/include/vmware_pack_begin.h
vmmon-only/include/vm_basic_asm.h
vmmon-only/include/crossgdt.h
vmmon-only/include/perfctr_generic.h
vmmon-only/include/vm_basic_asm_x86.h
vmmon-only/include/overheadmem_types.h
vmmon-only/include/compat_semaphore.h
vmmon-only/include/compat_kernel.h
vmmon-only/include/pageLock_defs.h
vmmon-only/include/rateconv.h
vmmon-only/include/x86_basic_defs.h
vmmon-only/include/ptsc.h
vmmon-only/include/x86perfctr.h
vmmon-only/include/basic_initblock.h
vmmon-only/include/x86desc.h
vmmon-only/include/versioned_atomic.h
vmmon-only/include/pcip_defs.h
vmmon-only/include/compat_ioport.h
vmmon-only/include/x86msr.h
vmmon-only/include/pshare_ext.h
vmmon-only/include/compat_spinlock.h
vmmon-only/include/monitorAction_exported.h
vmmon-only/include/usercalldefs.h
vmmon-only/include/vmmem_shared.h
vmmon-only/include/monLoader.h
vmmon-only/include/x86vendor.h
vmmon-only/include/iocontrols.h
vmmon-only/include/driver-config.h
vmmon-only/include/includeCheck.h
vmmon-only/include/circList.h
vmmon-only/include/compat_module.h
vmmon-only/include/contextinfo.h
vmmon-only/include/vmware_pack_init.h
vmmon-only/include/pgtbl.h
vmmon-only/include/vmm_constants.h
vmmon-only/include/x86paging_64.h
vmmon-only/include/monAddrLayout.h
vmmon-only/include/bootstrap_vmm.h
vmmon-only/include/vm_asm_x86.h
vmmon-only/include/vm_asm.h
vmmon-only/include/vm_time.h
vmmon-only/include/compat_highmem.h
vmmon-only/include/modulecall.h
vmmon-only/include/vcpuid.h
vmmon-only/include/vcpuset.h
vmmon-only/include/x86vt.h
vmmon-only/include/x86cpuid.h
vmmon-only/include/cpuid_info.h
vmmon-only/include/compat_cred.h
vmmon-only/include/compat_interrupt.h
vmmon-only/include/x86cpuid_asm.h
vmmon-only/include/vm_pagetable.h
vmmon-only/include/initblock.h
vmmon-only/include/monLoaderLog.h
vmmon-only/include/memDefaults.h
vmmon-only/include/numa_defs.h
vmmon-only/include/x86vt-vmcs-fields.h
vmmon-only/include/vm_atomic.h
vmmon-only/include/mon_assert.h
Traceback (most recent call last):
  File "./fixvm.py", line 107, in <module>
    vmwareFix()
  File "./fixvm.py", line 95, in vmwareFix
    copy2('/usr/lib/vmware/modules/source/vmnet-only/vmnet.ko', os.path.join('/lib/modules/', kernel_version, 'misc/'))
  File "/usr/lib64/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/lib/modules/4.12.8-300.fc26.x86_64/misc/'
```
My spec and details : 
https://gist.github.com/RobbiNespu/8a6febf7a4f5ba82388f37bed9e43839

**Comment by RobbiNespu** [comment]
Do some changes which failure for appending path for lib module and worked
```
git diff fixvm.py
diff --git a/fixvm.py b/fixvm.py
old mode 100644
new mode 100755
index 74acd94..b445465
--- a/fixvm.py
+++ b/fixvm.py
@@ -53,7 +53,7 @@ def vmISOK():
 
 # Checking whether Vmware installed or not [tested with VMWare Workstation]
 def vmwareInstalled():
-    if os.path.exists("/usr/bin/vmware"):
+    if os.path.exists("/usr/bin/vmplayer"):
         return True
     else:
         print("VMWare is not installed...")
@@ -87,12 +87,12 @@ def vmwareFix():
         os.system('tar cvf vmnet.tar vmnet-only')
         os.system('tar cvf vmmon.tar vmmon-only')
         try:
-            os.mkdir(os.path.join('/lib/modules/', kernel_version, 'misc'))
+            os.mkdir(os.path.join('/lib/modules/', kernel_version, '/misc'))
         # Contine if the directory exist
         except FileExistsError:
             pass
-        copy2('/usr/lib/vmware/modules/source/vmmon-only/vmmon.ko', os.path.join('/lib/modules/', kernel_version, 'misc'))
-        copy2('/usr/lib/vmware/modules/source/vmnet-only/vmnet.ko', os.path.join('/lib/modules/', kernel_version, 'misc/'))
+        copy2('/usr/lib/vmware/modules/source/vmmon-only/vmmon.ko', os.path.join('/lib/modules/', kernel_version, '/misc'))
+        copy2('/usr/lib/vmware/modules/source/vmnet-only/vmnet.ko', os.path.join('/lib/modules/', kernel_version, '/misc'))
         print(" Building VMWare modules ...")
         # Recompiling VMWARE modules
         os.system('depmod -a')

```

**Comment by hhemied** [comment]
I am glad that the code was helpful and thanks for your feedback.
Please try the updated version if you still have any issue with the previous one.
**## This issue will be closed...**
